"""empty message

Revision ID: 4252788ce9d9
Revises: 82662ee8d94a
Create Date: 2018-12-28 13:04:28.565358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4252788ce9d9'
down_revision = '82662ee8d94a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('favorite_color', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'favorite_color')
    # ### end Alembic commands ###
