"""empty message

Revision ID: 82662ee8d94a
Revises: 16d2cc5396eb
Create Date: 2018-12-28 12:49:24.413276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82662ee8d94a'
down_revision = '16d2cc5396eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'posts', 'users', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'author_id')
    # ### end Alembic commands ###
